# Limits and Continuity

## The Limit of a Function

Intuitive definition of limit

```{definition,name='Left Limit'}
We write $\lim_{{x \to c^-}} f(x) = L$ if the number $f(x)$ (the function height) keeps getting close to $L$ as $x$ approaches $c$ from the left.
```

```{definition,name='Right Limit'}
We write $\lim_{{x \to c^+}} f(x) = L$ if the number $f(x)$ (the function height) keeps getting close to $L$ as $x$ approaches $c$ from the right.
}

 Left Limit and Right Limit are called one-sided limits.
 
 
 
```{definition,name='Two-sided Limit'}
We write

$\lim_{{x \to c}} f(x) = L$

if the number $f(x)$ (the function height) keeps getting close to the
same value $L$ as $x$ approaches $c$ from either direction.
```

```{theorem}
The two-sided limit

$$\lim_{{x \to c}} f(x)$$

exists if and only if the two one-sided limits

$$\lim_{{x \to c^-}} f(x) \quad \text{and} \quad \lim_{{x \to c^+}} f(x)$$

both exist and are equal. Furthermore, if

$$\lim_{{x \to c^-}} f(x) = L \quad \text{and} \quad \lim_{{x \to c^+}} f(x) = L$$

then

$$\lim_{{x \to c}} f(x) = L.$$
```

``{example,name='Evaluating limits using a graph'
For each of the following functions, write down the left limit, right limit, two-sided limit, and the function value at the given point. If any limit is
undefined, write \"UND\".
-   at $x = 4$

-   at $x = 3$

-   at $x = 3$

-   at $x = 3$
```

```{Remark} In Example 3.1.5 part (a), you can observe that the
limit (two-sided limit) at $x = 2$ is equal to the function value at
that point. In part (d), you can observe that the limit (two-sided
limit) at $x = 3$ is different from the function value at that point. In
general, there is no connection between the limit of a function at a
point ($\lim_{{x \to c}} f(x)$) and the value of the function ($f(c)$)
at that point.

```

```{example}
Observing the table, we can say there is a good
chance that

$$\lim_{{x \to 0}} f(x) = 2.$$

One cannot use a table to calculate the limit exactly (Why?).
```


```{example}
The following figure shows the graph of
$f(x) = \sin\left(\frac{1}{x}\right)$. Observe that

$$\lim_{{x \to 0}} \sin\left(\frac{1}{x}\right)$$

is undefined.
```


Figure 3.1: Graph of $f(x) = \sin\left(\frac{1}{x}\right)$.

The graph is better than the table when we use Definition 3.1. In this
course, we stick with Definition 3.1. It's not rigorous enough; you will
learn the formal $\epsilon - \delta$ definition listed below in advanced
math classes.


```{definition}
Let $f: \mathbb{R} \to \mathbb{R}$ and
$L \in \mathbb{R}$. We say that the limit of $f$ at $c$ is $L$ and
denote it by

$$\lim_{{x \to c}} f(x) = L,$$

if for each $\epsilon > 0$, there exists $\delta > 0$ such that:

$$|x - c| < \delta \Rightarrow |f(x) - L| < \epsilon.$$
```


## Continuity

In the most basic sense, a continuous function can be sketched in one
continuous stroke without lifting a pen or pencil. We would need to lift
our pencil in drawing a function because it has a jump or hole in its
graph. If there is a jump or hole in the graph, at that point, either
the limit or function value is undefined, or they take different values.
This leads to the following definition.

```{definition, name='Continuity at a point'}
We say a function is continuous at a point $x = c$, if the number $f(x)$ (the function height) keeps getting close to $f(c)$ as $x$ approaches $c$ from either direction. A function that is not continuous at $c$ is said to have a
discontinuity at that point.
```


Following theorem is straightforward.


```{theorem,name='Continuity theorem I'}
A function $f$ is continuous
at a point $x = c$ if the following conditions are satisfied:

1.  $f(c)$ is defined;

2.  $\lim_{{x \to c}} f(x)$ is defined;

3.  $\lim_{{x \to c}} f(x) = f(c)$.
```

```{example}
For each of the following functions, state whether
the function is continuous at the given point. If not, state which
condition of continuity is broken at that point.

-   at $x = 4$

-   at $x = 2$

-   at $x = 2$

-   at $x = 3$
```


```{definition,name='Continuity of a function'}
A function is
**continuous on a set** $X$ if it is continuous at every point of $X$.
```


```{definition}
Let $f: \mathbb{R} \to \mathbb{R}$ and
$c \in \mathbb{R}$. $f$ is continuous at $c$ if for each $\epsilon > 0$,
there exists $\delta > 0$ such that:

$$|x - c| < \delta \Rightarrow |f(x) - f(c)| < \epsilon.$$
```


## Limits and Continuity

## Algebraic computation of limits

**Theorem 3.3.1. (Basic properties and rules for limits)**\
For any real number $c$, suppose that functions $f$ and $g$ both have
limits at $x = c$.

-   **Constant rule:** $\lim_{{x \to c}} k = k$.

-   **Multiple rule:**
    $\lim_{{x \to c}} [kf(x)] = k \lim_{{x \to c}} f(x)$ for any
    constant $k$.

-   **Sum rule:**
    $\lim_{{x \to c}} [f(x) + g(x)] = \lim_{{x \to c}} f(x) + \lim_{{x \to c}} g(x)$.

-   **Difference rule:**
    $\lim_{{x \to c}} [f(x) - g(x)] = \lim_{{x \to c}} f(x) - \lim_{{x \to c}} g(x)$.

-   **Product rule:**
    $\lim_{{x \to c}} [f(x) g(x)] = [\lim_{{x \to c}} f(x)][\lim_{{x \to c}} g(x)]$.

-   **Quotient rule:**
    $\lim_{{x \to c}} \frac{f(x)}{g(x)} = \frac{\lim_{{x \to c}} f(x)}{\lim_{{x \to c}} g(x)}$
    if $\lim_{{x \to c}} g(x) \neq 0$.

-   **Power rule:**
    $\lim_{{x \to c}} [f(x)]^n = [\lim_{{x \to c}} f(x)]^n$.

By using the $\epsilon - \delta$ definition of continuity and the above
theorem, we can establish the continuity of basic functions.

**Theorem 3.3.2.** Prove that $f(x) = x$ is continuous on the set of
real numbers.

**Proof.** For any $c \in \mathbb{R}$ and $\epsilon > 0$ let
$\delta = \epsilon$.

$$|x - c| < \delta \Rightarrow |x - c| < \epsilon \Rightarrow |f(x) - f(c)| < \epsilon$$

**Theorem 3.3.3. (Continuity theorem II)**\
If $f$ is a polynomial function, a rational function, a trigonometric
function, a trigonometric inverse function, an exponential function, or
a logarithmic function, then $f$ is continuous at any number $x = c$ for
which $f(c)$ is defined.

**Proof.**

*Remark 3.3.4.* We can plug in the value to find the limit only if we
know that the function is continuous at that point.

**Example 3.3.5.** Evaluate each of the following limits:

-   $\lim_{{x \to \frac{\pi}{6}}} \sin(x)$

-   $\lim_{{x \to \frac{\pi}{6}}} \cos(x)$

-   $\lim_{{x \to -\frac{\pi}{4}}} \sin(x)$

-   $\lim_{{x \to 2}} x$

-   $\lim_{{x \to \frac{\pi}{4}}} [\sin(x) + 2x + 3]$

-   $\lim_{{x \to \frac{\sqrt{3}}{2}}} [\sin^{-1}(x) + \cos^{-1}(x)]$

-   $\lim_{{x \to 2}} [2x^2 + 5x + 6]$

-   $\lim_{{x \to 6}} [\ln(x) + e^x]$

-   $\lim_{{x \to \frac{\pi}{6}}} \tan(x)$

-   $\lim_{{x \to 2}} [2x^2 + 5x + 6]$

-   $\lim_{{x \to \frac{\pi}{4}}} \frac{\sin(x) + \cos(x)}{\sin(x) \cos(x)}$

## Limits involving indeterminate forms

**Rational functions**

Evaluate $\lim_{{x \to 5}} \frac{x^2 - 11x + 30}{x^2 - 25}$

Let us try applying the Quotient rule:

$$\lim_{{x \to 5}} \frac{x^2 - 11x + 30}{x^2 - 25} = \frac{\lim_{{x \to 5}} [x^2 - 11x + 30]}{\lim_{{x \to 5}} [x^2 - 25]} = \frac{25 - 55 + 30}{25 - 25} = \frac{0}{0}$$

The denominator (namely $\lim_{{x \to 5}} [x^2 - 25]$) is zero;
therefore, we cannot use the Quotient rule here.

*Remark 3.4.1. (Indeterminate form)* In calculus and other branches of
mathematical analysis, an **indeterminate form** is an algebraic
expression obtained in the context of limits. Limits involving algebraic
operations are often performed by replacing expressions by their limits;
if the expression obtained after this substitution does not give enough
information to determine the original limit, it is known as an
indeterminate form. $\frac{0}{0}$ is one of the indeterminate forms you
will encounter in calculus 1.

Let us examine a method that can be used to go around this problem. We
want to evaluate $\lim_{{x \to 5}} \frac{x^2 - 11x + 30}{x^2 - 25}$.

Set $f(x) = \frac{x^2 - 11x + 30}{x^2 - 25}$ and we are looking for
$\lim_{{x \to 5}} f(x)$. Let us take a closer look at $f(x)$:

$$f(x) = \frac{x^2 - 11x + 30}{x^2 - 25} = \frac{(x - 5)(x - 6)}{(x - 5)(x + 5)} = \frac{x - 6}{x + 5} \quad \text{when } x \neq \pm 5$$

Still, 5 is not in the domain of $f$. Define a new function $g(x)$ by
$g(x) = \frac{x - 6}{x + 5}$. Observe that $g(x)$ is originally defined
as $\frac{x - 6}{x + 5}$ and 5 is in the domain of $g(x)$.

Now look at the graphs of $f(x)$ and $g(x)$. Observe that $g(x)$ is
defined and continuous at $x = 5$. Therefore, we can plug in 5 to get
$\lim_{{x \to 5}} g(x)$:

$$\lim_{{x \to 5}} g(x) = g(5) = \frac{5 - 6}{5 + 5} = -\frac{1}{10}$$

Of course, the graph of $f(x)$ has a hole at 5. Therefore, $f$ is not
continuous at 5. We cannot plug in 5 to get $\lim_{{x \to 5}} f(x)$, but
comparing the graphs of $f(x)$ and $g(x)$, one can observe that:

$$\lim_{{x \to 5}} f(x) = \lim_{{x \to 5}} g(x)$$

Since $\lim_{{x \to 5}} g(x) = -\frac{1}{10}$, $\lim_{{x \to 5}} f(x)$
is also $-\frac{1}{10}$.

The following summarizes the observations we made. Suppose
$R(x) = \frac{f(x)}{g(x)}$ and we want to evaluate
$\lim_{{x \to c}} R(x)$. Use of the quotient rule leads to the
indeterminate form $\frac{0}{0}$. The following steps might help to go
around this problem:

1.  Factor out the numerator and denominator.

2.  Cancel the common factors (bad guys).

3.  Use limits rules to evaluate the limit of the remaining function.

**Example 3.4.2.**
