# Series

## Introduction
Let the sequence $\{S_n\}$ be defined as follows:


\[
S_1 = 1
\]




\[
S_2 = 1 + 2 = 3
\]




\[
S_3 = 1 + 2 + 3 = 6
\]




\[
S_4 = 1 + 2 + 3 + 4 = 10
\]




By observing $\{S_n\}$, we conclude that the series $1 + 2 + 3 + 4 + \dots$ diverges.

To determine the behavior of $1 + 2 + 3 + \dots$, we need to compute $\lim_{n \to \infty} S_n$.

An **infinite series**, informally speaking, is the sum of the terms of an infinite sequence. It can be expressed in the form:


\[
a_1 + a_2 + a_3 + \dots = \sum_{i=1}^{\infty} a_i
\]



The $n$th **partial sum** of the series is:


\[
S_n = a_1 + a_2 + a_3 + \dots + a_n = \sum_{i=1}^{n} a_i
\]



The series is said to **converge** to the sum $S$ if the sequence of partial sums $\{S_n\}$ converges to $S$. In this case, we write:


\[
\sum_{i=1}^{\infty} a_i = \lim_{n \to \infty} S_n = S
\]



If the sequence does not converge, the series $\sum_{i=1}^{\infty} a_i$ **diverges** and does not have a sum.

## Sequence of Partial Sums

**Geometric Series**

A geometric sequence is one where each term is obtained by multiplying the previous term by a fixed ratio $r$.

For example:

- $2, 6, 18, 54, \dots$ has a common ratio of $r = 3$.
- $10, 5, 2.5, 1.25, \dots$ has a common ratio of $r = \frac{1}{2}$.

A geometric series has the form:


\[
a + ar + ar^2 + ar^3 + \dots = \sum_{i=0}^{\infty} ar^i
\]



```{theorem,name='The Convergence and Divergence of a Geometric Series'}


Consider the geometric series:


\[
a + ar + ar^2 + ar^3 + \dots + ar^{n-1} + \dots
\]



The sequence of partial sums is given by:


\[
S_n = \frac{a(1 - r^n)}{1 - r}, \quad \text{when } |r| < 1.
\]



- If \(|r| < 1\), the infinite series converges:


\[
\sum_{i=1}^\infty a_i = \frac{a}{1 - r}.
\]



- If \(|r| \geq 1\), the series \(\sum_{i=1}^\infty a_i\) diverges.

```

```{proof}


\begin{eqnarray}
S_n  &=& a + ar + ar^2 + \dots + ar^{n-1}\\
rS_n &=& ar + ar^2 + \dots + ar^n \\
S_n - rS_n &=& a - ar^n\\
S_n(1 - r) &=& a(1 - r^n)\\
S_n &=& \frac{a(1 - r^n)}{1 - r}
\end{eqnarray}

Taking the limit as \(n \to \infty\):


\begin{eqnarray}
\sum_{i=1}^\infty a_i 
&=& \lim_{n \to \infty} S_n\\
&=& \lim_{n \to \infty} \frac{a(1 - r^n)}{1 - r}\\
&=& \frac{a(1 - \lim_{n \to \infty} r^n)}{1 - r} \\
\end{eqnarray}

- When \(|r| < 1\), \(\lim_{n \to \infty} r^n = 0\), so:

\[
\sum_{i=1}^\infty a_i = \frac{a}{1 - r}.
\]

- When \(|r| \geq 1\), the series \(\sum_{i=1}^\infty a_i\) diverges.
```



```{example}
Find the Sum of the Following Infinite Series}

If it is divergent, write "Diverges."


a.  \( 1000, 500, 250, \dots \)
    
    This is a geometric series with a common ratio \( r = \frac{1}{2} < 1 \), hence:
    

\[
    \sum_{i=1}^\infty a_i = \frac{a}{1-r} = \frac{1000}{1 - \frac{1}{2}} = 2000
    \]



b. \( 0.1, 0.2, 0.4, \dots \)

    This is a geometric series with a common ratio \( r = 2 \), hence it diverges.

c. \( 1, \frac{1}{2}, \frac{1}{4}, \dots \)

    This is a geometric series with a common ratio \( r = \frac{1}{2} < 1 \), hence:
    

\[
    \sum_{i=1}^\infty a_i = \frac{a}{1-r} = \frac{1}{1 - \frac{1}{2}} = 2
    \]

```


```{example} 
Consider the Following Series


\[
\sum_{n=1}^\infty \frac{x^n}{3^n}
\]
```



Find the values of \( x \) for which the series converges.

First, observe that:
    

\[
    \sum_{n=1}^\infty \frac{x^n}{3^n} = \frac{x}{3} + \frac{x^2}{3^2} + \frac{x^3}{3^3} + \dots
    \]



This is a geometric series with a common ratio \( r = \frac{x}{3} \). The series will converge when:
    

\[
    \left|\frac{x}{3}\right| < 1 \quad \Rightarrow \quad -3 < x < 3
    \]



Find the sum of the series for those values of \( x \). Write the formula in terms of \( x \).

When \( |r| < 1 \), the sum of the geometric series is given by:
    

\[\sum_{n=1}^\infty a_i = \frac{a}{1-r}\]



Here:
    

\[\sum_{n=1}^\infty \frac{x^n}{3^n} = \frac{\frac{x}{3}}{1 - \frac{x}{3}} = \frac{x}{3 - x}\]




```{remark}
The function:


\[
f(x) = \frac{x}{3 - x}
\]


can be expressed as the limit of polynomial functions inside the interval \( -3 < x < 3 \):


\[
f(x) = \frac{x}{3 - x} = \lim_{k \to \infty} \sum_{n=1}^k \frac{x^n}{3^n}.
\]



Sometimes, properties of the terms of the sequence will be passed to the limit. Instead of studying the limiting function, we can study the behavior of simpler polynomial functions to understand the limiting function.

```